import React from 'react';
import { X, Printer, CheckCircle2 } from 'lucide-react';
import { getRecommendedTests } from '../data/labTests';

export default function DoctorSummaryModal({
  isOpen,
  onClose,
  assessment,
  bmiData,
  answers,
  questionsList,
  t
}) {
  if (!isOpen || !assessment) return null;

  const trans = t || {
    briefTitle: 'SheSync Clinical Consultation Brief',
    generatedOn: 'Generated',
    riskAssessment: 'Risk Assessment',
    identifiedPattern: 'Identified Pattern',
    primaryDriver: 'Primary Underlying Driver',
    calculatedBmi: 'Calculated BMI',
    menstrualPillar: 'Menstrual Pillar Score',
    androgenPillar: 'Androgenic Pillar Score',
    metabolicPillar: 'Metabolic Pillar Score',
    keyIndicators: 'Flagged Clinical Indicators',
    suggestedBloodwork: 'Suggested Diagnostic Bloodwork & Scans',
    doctorQuestions: 'Suggested Discussion Questions',
    disclaimer: 'Disclaimer: This summary is generated by an automated pattern screener and is intended solely for educational and clinical consultation facilitation. It does not constitute a formal diagnosis.',
    close: 'Close',
    printPdf: 'Print / Save PDF'
  };

  const { compositeScore, riskCategory, phenotype, subscores, flaggedSymptoms } = assessment;
  const recommendedTests = getRecommendedTests(subscores).filter((t) => t.isRecommended);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.75)',
        zIndex: 100,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px'
      }}
      onClick={onClose}
    >
      <div
        className="doctor-report-view"
        style={{
          width: '100%',
          maxWidth: '600px',
          maxHeight: '90vh',
          overflowY: 'auto'
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="doctor-report-header">
          <div>
            <div className="report-clinic-title">{trans.briefTitle}</div>
            <div className="report-date">
              {trans.generatedOn}: {new Date().toLocaleDateString()} | Rotterdam Screening Engine
            </div>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              className="header-action-btn no-print"
              onClick={handlePrint}
              title="Print Summary"
            >
              <Printer size={16} />
            </button>
            <button
              className="header-action-btn no-print"
              onClick={onClose}
              title={trans.close}
            >
              <X size={16} />
            </button>
          </div>
        </div>

        {/* Executive Summary Card */}
        <div
          style={{
            backgroundColor: 'var(--bg-subtle)',
            border: '2px solid var(--border-dark)',
            borderRadius: '12px',
            padding: '14px',
            display: 'flex',
            flexDirection: 'column',
            gap: '6px'
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '15px', fontWeight: '800', color: 'var(--text-main)' }}>
              {trans.riskAssessment}: {riskCategory} ({compositeScore}% Match)
            </span>
            <span
              className="progress-category-pill"
              style={{
                backgroundColor: compositeScore >= 65 ? '#B91C1C' : compositeScore >= 35 ? '#B45309' : '#047857',
                color: '#FFFFFF'
              }}
            >
              {phenotype.code}
            </span>
          </div>
          <div style={{ fontSize: '13px', color: 'var(--primary)', fontWeight: '800' }}>
            {trans.identifiedPattern}: {phenotype.name}
          </div>
          <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
            {trans.primaryDriver}: {phenotype.primaryDriver}
          </div>
        </div>

        {/* Patient Physical Markers */}
        {bmiData && (
          <div className="report-section">
            <div className="report-section-title">Physical & Metabolic Metrics</div>
            <table className="report-table">
              <tbody>
                <tr>
                  <td style={{ fontWeight: '700', width: '40%' }}>{trans.calculatedBmi}</td>
                  <td>{bmiData.bmi} kg/m² ({bmiData.category})</td>
                </tr>
                <tr>
                  <td style={{ fontWeight: '700' }}>{trans.menstrualPillar}</td>
                  <td>{subscores.menstrual}% Likelihood</td>
                </tr>
                <tr>
                  <td style={{ fontWeight: '700' }}>{trans.androgenPillar}</td>
                  <td>{subscores.androgen}% Likelihood</td>
                </tr>
                <tr>
                  <td style={{ fontWeight: '700' }}>{trans.metabolicPillar}</td>
                  <td>{subscores.metabolic}% Likelihood</td>
                </tr>
              </tbody>
            </table>
          </div>
        )}

        {/* Flagged Symptoms Table */}
        <div className="report-section">
          <div className="report-section-title">{trans.keyIndicators}</div>
          <table className="report-table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Symptom Question</th>
                <th>Patient Response</th>
              </tr>
            </thead>
            <tbody>
              {flaggedSymptoms.map((sym, idx) => (
                <tr key={idx}>
                  <td style={{ textTransform: 'capitalize', fontWeight: '700' }}>{sym.category}</td>
                  <td>{sym.title}</td>
                  <td style={{ fontWeight: '700', color: 'var(--red)' }}>{sym.response}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Recommended Lab Tests Checklist */}
        <div className="report-section">
          <div className="report-section-title">{trans.suggestedBloodwork}</div>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '6px' }}>
            {recommendedTests.map((testItem, i) => (
              <li
                key={i}
                style={{
                  fontSize: '12.5px',
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: '8px',
                  backgroundColor: 'var(--bg-subtle)',
                  padding: '8px 10px',
                  borderRadius: '8px',
                  border: '1px solid var(--border-light)'
                }}
              >
                <CheckCircle2 size={18} color="var(--primary)" style={{ minWidth: '18px', marginTop: '1px' }} />
                <div>
                  <span style={{ fontWeight: '800', color: 'var(--text-main)' }}>{testItem.name}</span> ({testItem.marker}):{' '}
                  <span style={{ color: 'var(--text-muted)' }}>{testItem.whyNeeded}</span>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* Questions for the Doctor */}
        <div className="report-section">
          <div className="report-section-title">{trans.doctorQuestions}</div>
          <ol style={{ paddingLeft: '20px', fontSize: '12.5px', color: 'var(--text-muted)', display: 'flex', flexDirection: 'column', gap: '4px' }}>
            <li>Would you recommend a transvaginal/pelvic ultrasound to evaluate ovarian follicle morphology?</li>
            <li>Should we order fasting insulin alongside fasting glucose to calculate my HOMA-IR score?</li>
            <li>Do my symptoms warrant evaluating free/total testosterone, DHEA-S, or an early follicular LH/FSH ratio?</li>
            <li>Can we screen thyroid (TSH/Free T4) and prolactin to rule out other ovulatory causes?</li>
          </ol>
        </div>

        {/* Disclaimer */}
        <div
          style={{
            fontSize: '11px',
            color: 'var(--text-light)',
            borderTop: '1px solid var(--border-light)',
            paddingTop: '8px',
            fontStyle: 'italic'
          }}
        >
          {trans.disclaimer}
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'flex', gap: '10px' }} className="no-print">
          <button className="btn-secondary" onClick={onClose} style={{ flex: 1 }}>
            {trans.close}
          </button>
          <button className="btn-primary" onClick={handlePrint} style={{ flex: 1 }}>
            <Printer size={16} />
            {trans.printPdf}
          </button>
        </div>
      </div>
    </div>
  );
}
